version: '3'
services:
  mongo:
    image: mongo
  virus_server:
    image: virus_server
    build: ./backend/coronavirus-visualizer-api
    environment:
      - MONGO_DB=mongo
      - VIRUS_DATA_API=virus_data_api:5000
      - HOST=0.0.0.0
    ports:
      - "4000:4000"
  virus_data_api:
    image: virus_data_api
    build: ./DataScraper
    ports:
      - "5000:5000"
