name: coronavirus_visualizer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  rxdart: ^0.23.1
  flutter_bloc: ^3.2.0
  equatable: ^1.1.0
  meta: ^1.1.6
  intl: ^0.16.0
  dio: ^3.0.8
  google_fonts: ^0.3.10
  charts_flutter: ^0.9.0
  localstorage: ^3.0.1+4
  flutter_slidable: "^0.5.4"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.4


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/thug_virus.png"

flutter_native_splash:
  image: assets/splash.png
  color: "000000"

flutter:
  assets:
    - assets/
    - google_fonts/
  fonts:
    - family: Baloo
      fonts:
        - asset: google_fonts/Baloo-ExtraBold.ttf

  # the material Icons class.
  uses-material-design: true
